CREATE TABLE FARMTECH_SENSORES (
    SENSOR_ID NUMBER,
    TEMPERATURA NUMBER(5,2),
    UMIDADE NUMBER(5,2),
    LUMINOSIDADE NUMBER,
    STATUS_IRRIGACAO VARCHAR2(10),
    DATA_LEITURA VARCHAR2(20)
    );
    
    ##Mostrar todos os dados
    SELECT * FROM FARMTECH_SENSORES;
    
    ##Média da Temperatura
    SELECT AVG(TEMPERATURA) AS MEDIA_TEMPERATURA
    FROM FARMTECH_SENSORES;
    
    ##Sensores com baixa umidade
    SELECT *
    FROM FARMTECH_SENSORES
    WHERE UMIDADE < 30;
    
    ##Irrigação ligada
    SELECT *
    FROM FARMTECH_SENSORES
    WHERE STATUS_IRRIGACAO = 'ON';